Repository stefanpenner/ember-cli-addon-aware-resolver, pull requests merged in 2023-08, with the labels that each got.

#12 chore: bump Node versions
  .github/workflows/ci.yml
Labels: breaking

#11 Set default import path
  .gitignore
  index.js
  package.json
  tests/index-test.js
Labels: bug

#13 Make `IdentifierRegexp` public, add `throwOnMissingFile` option
  index.js
  tests/index-test.js
Labels: enhancement
